### ISSUE TITLE
'go get github.com/jpoles1/gopherbadger' doesn't install latest version

### ISSUE THREAD

**Issue by seenickcode** [jpoles1/gopherbadger#11]
I'd like to use the `-covercmd` flag incorporated via this [PR](https://github.com/jpoles1/gopherbadger/pull/10/files). 

When run `go get github.com/jpoles1/gopherbadger` and run `gopherbadger -covercmd` it says the flag is not recognized. Yet when I run `go build *.go` in the actual source directory, I can then use that flag properly.

Would you know why the `go get` command above doesn't seem to install the latest binary to my $GOROOT/bin?

**Comment by jpoles1** [comment]
Sorry I've left this issue hanging! 

Unfortunately, not sure what might be causing this issue. Have you been able to get it working in the interim?

Do you have any ideas @award28?

**Comment by award28** [comment]
@jpoles1, unfortunately, I'm just seeing this too. 

@seenickcode Can you share a little bit more with us? Do you have a link to your repository? Since you're using $GOROOT, try using go modules, and let me know if the coverage command works. It shouldn't make a difference, but that's how I used it.

As a response to this issue, I'll raise a new PR with an example layout that worked for me.

**Comment by award28** [comment]
@jpoles1 can you assign this issue to me?

**Comment by daltemen** [comment]
I think it is necessary to make a tag of a new release. 
I tested with go1.13 and go mod.
`github.com/jpoles1/gopherbadger v2.1.1+incompatible // indirect` 
was the version downloaded.

**Comment by jpoles1** [comment]
Thanks for the suggestion @daltemen. Created a new tag, hopefully that should fix the issue!

**Comment by daltemen** [comment]
Would you try tagging `v2.2.0` version ? with `2.2` version doesn't seem to work.

**Comment by jpoles1** [comment]
Done, hopefully that does it @daltemen! Thanks for the help

**Comment by daltemen** [comment]
It works like a charm. Thanks @jpoles1

**Comment by jpoles1** [comment]
Wonderful, thanks again @daltemen!
