### ISSUE TITLE
Aggregate coverage value across packages

### ISSUE THREAD

**Issue by jnadler** [jpoles1/gopherbadger#2]
I just tried this out - nice work btw!
Unfortunately it doesn't seem to work with multiple packages, which is a shame because a single coverage % value across the whole project is really the key thing I'm after.    The value in the badge is the coverage from the first package only.    
To test across all packages I ran `go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o=coverage.html`

**Comment by jpoles1** [comment]
Hey @jnadler, thanks for bringing this up. I'm actually working on a project with such a structure now, and I ran into the same issue. I've got to implement a solution, I think I'll use:
`go tool cover -func=coverage.out`

**Comment by jpoles1** [comment]
I think the following bash command should work for most projects:
`go test ./... -coverprofile=coverage.out && go tool cover -func=coverage.out` 

@jnadler, when run on your project, does this seem to work, and generate a line akin to: 
`total:                                                  (statements)            74.6%`

**Comment by jpoles1** [comment]
Alrighty, @jnadler I think the above fix should work. Please give it a try and let me know!

**Comment by jnadler** [comment]
Well that's closer, but in this project there are still some packages with no tests whatsoever, and so we get a vastly inflated coverage number (coverage is good in the packages with tests).   

That's no fault of your software however.   I've just found this bug which seems to cover it:
https://github.com/golang/go/issues/24570

I'll close this as there seems to be nothing you can do until they fix that one.   Thanks for the speedy response, and for sharing this tool!!

**Comment by jnadler** [comment]
I should mention - I think that change is good, and I appreciate that it doesn't depend on specific makefile setup.    IMO it would be good to merge that change to master, though it might require a small change to the readme.
