### ISSUE TITLE
Customize Command

### ISSUE THREAD

**Issue by jnadler** [jpoles1/gopherbadger#5]
Would it be possible to add a command line arg that lets a user specify the command to run?  It would override the default command here, and obviously it would have to be something that spits out a coverage report:
https://github.com/jpoles1/gopherbadger/blob/master/main.go#L86

I'm modifying the 'coverage.out' to remove generated code, so I'd like to override it to not rerun test and instead use the output of the tests I already ran. 
 I could take a swing at a PR if you're busy.  Thanks!

Jeff

**Comment by jpoles1** [comment]
Sounds like a nice feature to me! Please give the PR a go, and we can work from there.

**Comment by jnadler** [comment]
Done, here's the PR:  https://github.com/jpoles1/gopherbadger/pull/6

**Comment by jpoles1** [comment]
What a lovely lil PR, thanks so much @jnadler! Should we add something to the README describing your contribution? Perhaps you can describe your use case in a little more detail.

**Comment by jnadler** [comment]
One thing I like about this is that now my `Makefile` doesn't run tests twice to generate a badge.   I have a `test` target and the `cover` target depends on it, so gopherbadger only runs `go tool cover`.

More critically, having them separated lets me modify the coverage.out file in-between.   I have some generated mocks and some integration tests that should not be included in the coverage calc, so I can use `grep -v` to remove those before gopherbadger runs.   It's a bit of a hack but there's no real flexible way to exclude code from coverage otherwise!
