### ISSUE TITLE
Allow code coverage with build tags

### ISSUE THREAD

**Issue by award28** [jpoles1/gopherbadger#9]
Golang allows build tags, and currently there is no option to test code coverage by build tags. This feature would allow the execution by `$GOBIN/gopherbadger -tags "TAG1 TAG2"` and will test on those tags.

**Comment by award28** [comment]
One solution is to use the -covercmd as so:
`$GOBIN/gopherbadger -covercmd "go test -tags \"TAG1 TAG2\" ./... -coverprofile=coverage.out && go tool cover -func=coverage.out"`

but I think it would be cleaner if we integrate the tags option directly. If you agree (@jpoles1 ), I'll work on the PR.

**Comment by jpoles1** [comment]
Thanks for the suggestion @award28! I think that's a great idea, will happily incorporate your PR.

**Comment by jpoles1** [comment]
@award28, would also appreciate if you could update the README in your PR to incorporate a brief documentation for any new cmdline args you add. Thanks again!

**Comment by award28** [comment]
@jpoles1 Just put in the PR. Let me know if you have any questions.

**Comment by jpoles1** [comment]
Excellent work @award28, thank you again for your contribution!
